### ISSUE TITLE
request of projection layer weight

### ISSUE THREAD

**Issue by seungheondoh** [descriptinc/lyrebird-wav2clip#19]
Hi @hohsiangwu , Thanks for great work!
Request pre-trained weights of `image_transform (MLP layer)` for audio-image-language joint embedding space.

Currently, only audio encoders seem to exist in the `get_model` function. 
Is there any big problem if I use CLIP embedding (text or image) without projection layer?

**Comment by hohsiangwu** [comment]
The audio projection layer is used to project audio modality onto the same embedding space as the original CLIP. Therefore, the CLIP (image and text) embedding without the projection should make more sense to align with the audio with the projection.

**Comment by seungheondoh** [comment]
Thank you for answer! Noticed that the `transformed_audio` does a similarity operation with `image_out` (clip space), not `transformed_image`!

```
loss = (
    self.loss_fn_a(audio_out, transformed_image)
    + self.loss_fn_i(transformed_audio, image_out)
) / 2
```
